import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Material Design 3 tokens (Stitch design system)
        primary: "#006b5f",
        "on-primary": "#ffffff",
        "primary-container": "#14b8a6",
        "on-primary-container": "#00423b",
        "primary-fixed": "#71f8e4",
        "primary-fixed-dim": "#4fdbc8",
        "inverse-primary": "#4fdbc8",
        secondary: "#555f6d",
        "on-secondary": "#ffffff",
        "secondary-container": "#d6e0f1",
        "on-secondary-container": "#596372",
        "secondary-fixed": "#d9e3f4",
        "secondary-fixed-dim": "#bdc7d8",
        "on-secondary-fixed": "#121c28",
        "on-secondary-fixed-variant": "#3e4755",
        tertiary: "#b91a24",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#ff7d76",
        "on-tertiary-container": "#7b000e",
        "tertiary-fixed": "#ffdad7",
        "tertiary-fixed-dim": "#ffb3ad",
        "on-tertiary-fixed": "#410004",
        "on-tertiary-fixed-variant": "#930013",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#f9f9f7",
        "on-background": "#1a1c1b",
        surface: "#f9f9f7",
        "on-surface": "#1a1c1b",
        "surface-variant": "#e2e3e1",
        "on-surface-variant": "#3c4947",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f4f2",
        "surface-container": "#eeeeec",
        "surface-container-high": "#e8e8e6",
        "surface-container-highest": "#e2e3e1",
        "surface-bright": "#f9f9f7",
        "surface-dim": "#dadad8",
        "surface-tint": "#006b5f",
        "inverse-surface": "#2f3130",
        "inverse-on-surface": "#f1f1ef",
        outline: "#6c7a77",
        "outline-variant": "#bbcac6",
        // Legacy teal scale (backward compat)
        teal: {
          50:  "#f0fdfa",
          100: "#ccfbf1",
          200: "#99f6e4",
          300: "#5eead4",
          400: "#2dd4bf",
          500: "#14b8a6",
          600: "#0d9488",
          700: "#0f766e",
          800: "#115e59",
          900: "#134e4a",
        },
      },
      fontFamily: {
        headline: ['"Plus Jakarta Sans"', '"Noto Sans JP"', "sans-serif"],
        body:     ["Inter", '"Noto Sans JP"', "sans-serif"],
        label:    ["Inter", '"Noto Sans JP"', "sans-serif"],
        sans:     ["Inter", '"Noto Sans JP"', "sans-serif"],
      },
      borderRadius: {
        sm:   "0.25rem",
        DEFAULT: "0.375rem",
        md:   "0.5rem",
        lg:   "0.75rem",
        xl:   "1rem",
        "2xl":"1.5rem",
        full: "9999px",
      },
      boxShadow: {
        card:       "0 2px 12px -2px rgba(0,107,95,0.06)",
        "card-hover":"0 8px 24px -4px rgba(0,107,95,0.10)",
        float:      "0 12px 32px -4px rgba(0,107,95,0.12)",
        glass:      "0 4px 24px -2px rgba(0,107,95,0.08)",
      },
      backgroundImage: {
        "editorial-gradient": "linear-gradient(135deg, #006b5f 0%, #14b8a6 100%)",
      },
    },
  },
  plugins: [],
};
export default config;
